# Getting started with pandas

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

## pandas的数据结构介绍

### Series

In [2]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
# 获取值的数组表示形式
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
# 获取索引对象
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
# 带有索引的Series
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2['a']

-5

In [8]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [9]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [10]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [11]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
'b' in obj2

True

In [13]:
'e' in obj2

False

In [14]:
# 通过字典来创建Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [15]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [16]:
# isnull检测缺失数据
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [18]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [20]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
# 自动对齐索引并求和
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [22]:
# 设置name属性
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [23]:
# 通过赋值修改索引
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [24]:
# 通过字典创建DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [25]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [26]:
# 如果指定了列，则DataFrame的列会按照指定顺序进行排列
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [27]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [28]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [29]:
# 通过字典方式获取列
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [30]:
# 通过属性方式获取列
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [31]:
# 通过ix字段获取行
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [32]:
# 给空的debt列赋上一个标量值
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [33]:
# 给空的debt列赋上一组值
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [34]:
# 将数组或列表赋值给某个列时，其长度必须跟DataFrame长度匹配，如果赋值的是一个Series，则会匹配索引，空位填补上缺失值
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [35]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [36]:
# 删除列
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [37]:
# 嵌套字典，外层为列，内层为行
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [38]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [39]:
# 转置
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [40]:
# 显示指定了索引
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [41]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [42]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [43]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [44]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### 索引对象

In [45]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [46]:
index[1:]

Index(['b', 'c'], dtype='object')

In [47]:
# index对象是不可修改的
index[1] = 'd'

TypeError: Index does not support mutable operations

In [ ]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

In [ ]:
frame3

In [ ]:
'Ohio' in frame3.columns

In [ ]:
2003 in frame3.index

## 基本功能

### 重新索引

In [48]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [49]:
# 索引不存在就引入缺失值
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [50]:
# 缺失值用0填补
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [51]:
# 插值并向前填充
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [52]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [53]:
# 只传入一个序列会重新索引行
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [54]:
# 利用columns重新索引列
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [55]:
# 同时对行列进行重新索引，但插值只对行应用
frame.reindex(index=['a', 'b', 'c', 'd'], method='ffill',
              columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [56]:
# 利用ix标签重新索引
frame.ix[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### 丢弃指定轴上的项

In [57]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [58]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [59]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

In [60]:
# 默认选取行标
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [61]:
# 通过修改axis选取列标
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [62]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### 索引、选取和过滤

In [63]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj['b']

1.0

In [64]:
obj[1]

1.0

In [65]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [66]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [67]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [68]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [69]:
# 标签切片包含末端
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [70]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [71]:
# 对DataFrame进行索引就是获取一个或多个列
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [72]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [73]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [74]:
# 通过切片选取则有点特殊
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [75]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [76]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [77]:
data[data < 5] = 0

In [78]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [79]:
data.ix['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [80]:
data.ix[['Colorado', 'Utah'], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [81]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [82]:
data.ix[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [83]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 算数运算和数据对齐

In [84]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [85]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [86]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [87]:
# 缺失值会在算数运算中传播
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [88]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [89]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [90]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

#### 在算数方法中填充值

In [91]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [92]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [93]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [94]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [95]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### DataFrame和Series之间的运算

In [96]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [97]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [98]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [99]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.ix[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [100]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [101]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [102]:
series2 = Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [103]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [104]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [105]:
# 在列上进行广播
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 函数应用和映射

In [106]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [107]:
frame

b         d         e
Utah   -0.122554 -0.114762 -0.696050
Ohio    1.534720 -0.984056  0.600484
Texas   0.194517  0.264743 -1.643260
Oregon -0.841009  0.671687 -0.778545

In [108]:
np.abs(frame)

b         d         e
Utah    0.122554  0.114762  0.696050
Ohio    1.534720  0.984056  0.600484
Texas   0.194517  0.264743  1.643260
Oregon  0.841009  0.671687  0.778545

In [109]:
f = lambda x: x.max() - x.min()

In [110]:
# 默认在列上
frame.apply(f)

b    2.375730
d    1.655743
e    2.243743
dtype: float64

In [111]:
frame.apply(f, axis=1)

Utah      0.581288
Ohio      2.518776
Texas     1.908003
Oregon    1.512696
dtype: float64

In [112]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.841009 -0.984056 -1.643260
max  1.534720  0.671687  0.600484

In [113]:
# 将frame中各个浮点值格式化
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.12  -0.11  -0.70
Ohio     1.53  -0.98   0.60
Texas    0.19   0.26  -1.64
Oregon  -0.84   0.67  -0.78

In [114]:
# # 将Series中各个浮点值格式化
frame['e'].map(format)

Utah      -0.70
Ohio       0.60
Texas     -1.64
Oregon    -0.78
Name: e, dtype: object

### 排序和排名

In [115]:
# 对索引进行排序
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [116]:
# DataFrame默认对行索引进行排序
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [117]:
# 通过axis对列索引进行排序
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [118]:
# 降序排序
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [119]:
# 对值进行排序
obj = Series([4, 7, -3, 2])
obj.order()

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: order is deprecated, use sort_values(...)
  app.launch_new_instance()


2   -3
3    2
0    4
1    7
dtype: int64

In [120]:
# 如果有缺失值则放在末尾
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj.order()

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: order is deprecated, use sort_values(...)
  app.launch_new_instance()


4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [121]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [122]:
# 对某一列的值进行排序
frame.sort_index(by='b')

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  from ipykernel import kernelapp as app


a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [123]:
frame.sort_index(by=['a', 'b'])

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':


a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [124]:
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [125]:
# 根据值在原数据中出现的顺序给出排名
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [126]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [127]:
frame = DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                   'c': [-2, 5, 8, -2.5]})
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [128]:
# 在行上进行排名
frame.rank(axis=1)

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

### 带有重复值的轴索引

In [129]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [130]:
# is_unique属性判断值是否唯一
obj.index.is_unique

False

In [131]:
# 索引对应多个值，返回一个Series
obj['a']

a    0
a    1
dtype: int32

In [132]:
obj['c']

4

In [133]:
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  0.84162  1.881148  0.171476
a  1.94022 -0.647735 -0.292466
b  0.30396  0.327782 -1.336634
b -0.70520 -0.319087  1.093820

In [134]:
# 进行行索引
df.ix['b']

0         1         2
b  0.30396  0.327782 -1.336634
b -0.70520 -0.319087  1.093820

## 汇总和计算描述统计

In [135]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], 
               index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [136]:
# DataFrame的sum方法将会返回一个带有列小计的Series
df.sum()

one    9.25
two   -5.80
dtype: float64

In [137]:
# 按行进行求和运算
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [138]:
# NA值会被自动排除，通过skipna选项可以禁用
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [139]:
# 列中达到最大值的行索引
df.idxmax()

one    b
two    d
dtype: object

In [140]:
# 计算累计值
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [141]:
# 产生汇总统计
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [142]:
# 非数值型数据的汇总统计
obj = Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### 唯一值、值计数以及成员资格

In [143]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [144]:
# 获取Series中唯一值数组(未排序，可以用uniques.sort()排序)
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [145]:
# 计算Series中各值出现的频率
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [146]:
# 顶级pandas方法
pd.value_counts(obj.values, sort=False)

a    3
d    1
b    2
c    3
dtype: int64

In [147]:
# 判断矢量化集合的成员资格
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [148]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

## 处理缺失数据

In [149]:
string_data = Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [150]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [151]:
# Python内置的None值也会被当作NA处理
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 滤除缺失数据

In [152]:
from numpy import nan as NA
data = Series([1, NA, 3.5, NA, 7])
# dropna返回一个仅含飞控数据和索引值的Series
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [153]:
# 通过布尔型索引也可以达到这个目的
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [154]:
# 对于DataFrame对象，dropna默认丢弃任何含有缺失值的行
data = DataFrame([[1., 6.5, 3.], [1., NA, NA],
                  [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [155]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [156]:
# 传入how='all'将只丢弃全为NA的那些行
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [157]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [158]:
# 要用这种方式丢弃列，只需要传入axis=1即可
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [159]:
df = DataFrame(np.random.randn(7, 3))
df.ix[:4, 1] = NA; df.ix[:2, 2] = NA
df

0         1         2
0 -0.388116       NaN       NaN
1  0.259971       NaN       NaN
2  0.802000       NaN       NaN
3 -0.144973       NaN  0.055560
4 -2.097709       NaN  0.607396
5  0.092182  0.965297  0.076064
6 -0.423525 -0.493101  0.269781

In [160]:
# 过滤数据，确保每行中至少有3个非NA值数据
df.dropna(thresh=3)

0         1         2
5  0.092182  0.965297  0.076064
6 -0.423525 -0.493101  0.269781

In [161]:
df.dropna(thresh=2)

0         1         2
3 -0.144973       NaN  0.055560
4 -2.097709       NaN  0.607396
5  0.092182  0.965297  0.076064
6 -0.423525 -0.493101  0.269781

### 填充缺失数据

In [162]:
# 通过一个常数调用fillna就会将缺失值替换为那个常数值
df.fillna(0)

0         1         2
0 -0.388116  0.000000  0.000000
1  0.259971  0.000000  0.000000
2  0.802000  0.000000  0.000000
3 -0.144973  0.000000  0.055560
4 -2.097709  0.000000  0.607396
5  0.092182  0.965297  0.076064
6 -0.423525 -0.493101  0.269781

In [163]:
# 对不同的列填充不同的值
df.fillna({1: 0.5, 3: -1})

0         1         2
0 -0.388116  0.500000       NaN
1  0.259971  0.500000       NaN
2  0.802000  0.500000       NaN
3 -0.144973  0.500000  0.055560
4 -2.097709  0.500000  0.607396
5  0.092182  0.965297  0.076064
6 -0.423525 -0.493101  0.269781

In [164]:
# fillna默认返回新对象，但也可以对现有对象进行修改
_ = df.fillna(0, inplace=True)
df

0         1         2
0 -0.388116  0.000000  0.000000
1  0.259971  0.000000  0.000000
2  0.802000  0.000000  0.000000
3 -0.144973  0.000000  0.055560
4 -2.097709  0.000000  0.607396
5  0.092182  0.965297  0.076064
6 -0.423525 -0.493101  0.269781

In [165]:
# 对reindex有效的那些插值方法也可以用于fillna
df = DataFrame(np.random.randn(6, 3))
df.ix[2:, 1] = NA; df.ix[4:, 2] = NA
df

0         1         2
0 -0.550082  0.333735  0.353167
1 -0.856167 -0.243431  0.743591
2  1.203641       NaN -0.164750
3 -0.957399       NaN  1.324774
4  0.722980       NaN       NaN
5  0.442570       NaN       NaN

In [166]:
df.fillna(method='ffill')

0         1         2
0 -0.550082  0.333735  0.353167
1 -0.856167 -0.243431  0.743591
2  1.203641 -0.243431 -0.164750
3 -0.957399 -0.243431  1.324774
4  0.722980 -0.243431  1.324774
5  0.442570 -0.243431  1.324774

In [167]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -0.550082  0.333735  0.353167
1 -0.856167 -0.243431  0.743591
2  1.203641 -0.243431 -0.164750
3 -0.957399 -0.243431  1.324774
4  0.722980       NaN  1.324774
5  0.442570       NaN  1.324774

In [168]:
# 传入平均值
data = Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 层次化索引

In [169]:
# 能使一个轴上拥有多个索引级别，让我们能以低维度形式处理高维度数据
data = Series(np.random.randn(10),
              index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                     [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])
data

a  1    0.224558
   2   -1.785922
   3   -2.072599
b  1    0.694736
   2   -0.677001
   3    1.592473
c  1   -0.879114
   2    1.014210
d  2    2.367264
   3    1.220802
dtype: float64

In [170]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 1, 2]])

In [171]:
data['b']

1    0.694736
2   -0.677001
3    1.592473
dtype: float64

In [172]:
data['b':'c']

b  1    0.694736
   2   -0.677001
   3    1.592473
c  1   -0.879114
   2    1.014210
dtype: float64

In [173]:
data.ix[['b', 'd']]

b  1    0.694736
   2   -0.677001
   3    1.592473
d  2    2.367264
   3    1.220802
dtype: float64

In [174]:
# 在内层中进行选取
data[:, 2]

a   -1.785922
b   -0.677001
c    1.014210
d    2.367264
dtype: float64

In [175]:
data.unstack()

1         2         3
a  0.224558 -1.785922 -2.072599
b  0.694736 -0.677001  1.592473
c -0.879114  1.014210       NaN
d       NaN  2.367264  1.220802

In [176]:
data.unstack().stack()

a  1    0.224558
   2   -1.785922
   3   -2.072599
b  1    0.694736
   2   -0.677001
   3    1.592473
c  1   -0.879114
   2    1.014210
d  2    2.367264
   3    1.220802
dtype: float64

In [177]:
# 对于一个DataFrame，每条轴都可以有分层索引
frame = DataFrame(np.arange(12).reshape((4, 3)),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=[['Ohio', 'Ohio', 'Colorado'],
                           ['Green', 'Red', 'Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [178]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [179]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

### 重排分级顺序

In [181]:
# swaplevel接受两个级别编号或名称
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [182]:
# 根据单个级别中的值对数据进行排序
frame.sortlevel(1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [183]:
frame.sortlevel(0)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [184]:
frame.swaplevel(0, 1).sortlevel(0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

### 根据级别汇总统计

In [185]:
frame.sum(level='key2')

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [186]:
frame.sum(level='color', axis=1)

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

### 使用DataFrame的列

In [187]:
frame = DataFrame({'a': range(7), 'b': range(7, 0, -1),
                   'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
                   'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [188]:
# DataFrame的set_index函数会将其一个或多个列转换为行索引，并创建一个新的DataFrame
frame2 = frame.set_index(['c', 'd'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [189]:
# 默认情况下，那些列会从DataFrame中移除，但也可以将其保留下来
frame.set_index(['c', 'd'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [190]:
# reset_index的功能和set_index刚好相反，层次化索引的级别会被转移到列里面
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1